### ISSUE TITLE
Can not deploy private registry docker images

### ISSUE THREAD

**Issue by r-chris** [nulldriver/cf-cli-resource#24]
Manifest file:
```
applications:
- name: test-deploy-private
  docker:
    image: PRIVATE_DOCKER_REGISTRY_NAME/test-app:latest
    username: ***
  command: null
  memory: 128M
  instances: 1
  disk_quota: 5G
  health-check-type: process
  routes:
    - route: test-deploy-private.***
```

Deployment plan:
```
- name: deploy-cli-private
  plan:
  - get: git
    passed: [build-private]
    trigger: false
  - put: cf-cli-env
    params:
      command: push
      manifest: git/manifest-private.yml
      environment_variables:
        CF_DOCKER_PASSWORD: ((docker-registry-password))
      cf_trace: true
```

Error message:
```
Using manifest file git/manifest-private.yml

FAILED
No Docker password was provided. Please provide the password by setting the CF_DOCKER_PASSWORD environment variable.
```
