### ISSUE TITLE
Error with push command since last realease

### ISSUE THREAD

**Issue by xNok** [nulldriver/cf-cli-resource#39]
Since the latest relase I am unable to use the command push properly

```
   - put: pcf
      params:
        name: simulation
        manifest: simulation/ci/manifest-dev.yml
        path: artifactory-rc/simulation-*.jar
```
I get the following error:
```
Incorrect Usage: The specified path 'artifactory-rc/simulation-*.jar' does not exist.
```
While the file does exit, also and I have ben using the same pipeline for a couple day without amy trouble
