### ISSUE TITLE
set-env should support multiple environment variables

### ISSUE THREAD

**Issue by patrickcrocker** [nulldriver/cf-cli-resource#71]
Instead of this:
```yml
  - put: cloud-foundry
    params:
      commands:
      - command: set-env
        app_name: myapp-ui
        env_var_name: SOME_KEY
        env_var_value: SOME_VALUE
      - command: set-env
        app_name: myapp-ui
        env_var_name: SOME_OTHER_KEY
        env_var_value: SOME_OTHER_VALUE
```

let's support this:
```yml
  - put: cloud-foundry
    params:
      commands:
      - command: set-env
        app_name: myapp-ui
        environment_variables:
          SOME_KEY: SOME_VALUE
          SOME_OTHER_KEY: SOME_OTHER_VALUE
```

This is also consistent with how env vars are passed to `zero-downtime-push` (and soon `push` as well).
