### ISSUE TITLE
environment_variables not getting passed 

### ISSUE THREAD

**Issue by destasys** [nulldriver/cf-cli-resource#74]
When I run a cf push as follows, environment_variables not getting passed to cf, any ideas?
```
          resource: cf-env
          params:
            command: push
            command_file: cf_command/params.yml
```

```
docker_image: example.com/docker/dotnet-example-api:1.4.0
command: push
app_name: example-app
instances: 2
memory: 512M
docker_username: ((username))
docker_password: ((password))
environment_variables:
  AspnetCore__Authentication__Instance: https://idp.example.com
  AspnetCore__cors__origins__entries__0: https://ui.example.com
  NEW_RELIC_LICENSE_KEY: YOUR_KEY
  NEW_RELIC_APP_NAME: YOUR_APP_NAME


```

**Comment by destasys** [comment]
@patrickcrocker  can you please review and merge my PR?

**Comment by patrickcrocker** [comment]
This feature hadn't actually been released yet.  I've just now released this in [v2.18.0](https://github.com/nulldriver/cf-cli-resource/releases/tag/v2.18.0)

I should probably take a look at commiting changes to a `dev` branch until ready for release.  That way there won't be a disparity between what's in trunk and what's been released.

**Comment by destasys** [comment]
@patrickcrocker  

I just tried using v 2.18.0 and env vars are **not** getting passed 

the resource in my ci pipeline.yml

```
  - name: cf-cli-resource
    type: docker-image
    source: 
      repository: nulldriver/cf-cli-resource
      tag: 2.18.0
```

the push


```
  - name: deploy-to-sandbox
    plan:
        - get : app-repo
        - get: version 
          trigger: true
          passed: [build-and-publish]
        - task: create-deploy-params
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
               repository: busybox
            inputs:
                - name: version
            run:
              path: sh
              args: 
                - -exc
                - |- 
                 cat version/docker | xargs -I {} -n 1 echo 'docker_image: example.com/docker/architecture-na/react-sample-ui:{}' > cf_command/params.yml 
                 cat >> cf_command/params.yml <<EOF
                 command: push
                 app_name: react-example-ui
                 instances: 2
                 memory: 512M
                 docker_username: ((proget-user))
                 docker_password: ((proget-password))
                 environment_variables:
                   SITE_SETTINGS: '{"API_URL":"api.example.com" ,  "ANOTHER_API_URL" : "anotherapi.example.com" }'
                   KEY: VALUE 
                 EOF
            outputs:
              - name: cf_command
        - put: run-container-image
          inputs:
            - cf_command
            - app-repo
          resource: cf-sandbox
          params:
            command: push
            command_file: cf_command/params.yml

```



logs from concourse 

```
Using manifest file /tmp/build/put/manifest-for-environment-variables.yml


Deprecation warning: Specifying app manifest attributes at the top level is deprecated. Found: env.
Please see https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#deprecated for alternatives and other app manifest deprecations. This feature will be removed in the future.


Using manifest file manifest-for-environment-variables.yml
```
