### ISSUE TITLE
@patrickcrocker

### ISSUE THREAD

**Issue by destasys** [nulldriver/cf-cli-resource#76]
@patrickcrocker  

I just tried using v 2.18.0 and env vars are **not** getting passed 

the resource in my ci pipeline.yml

```
  - name: cf-cli-resource
    type: docker-image
    source: 
      repository: nulldriver/cf-cli-resource
      tag: 2.18.0
```

the push

```
  - name: deploy-to-sandbox
    plan:
        - get : app-repo
        - get: version 
          trigger: true
          passed: [build-and-publish]
        - task: create-deploy-params
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
               repository: busybox
            inputs:
                - name: version
            run:
              path: sh
              args: 
                - -exc
                - |- 
                 cat version/docker | xargs -I {} -n 1 echo 'docker_image: example.com/docker/repo/react-sample-ui:{}' > cf_command/params.yml 
                 cat >> cf_command/params.yml <<EOF
                 command: push
                 app_name: react-example-ui
                 instances: 2
                 memory: 512M
                 docker_username: (user))
                 docker_password: (password))
                 environment_variables:
                   SITE_SETTINGS: '{"API_URL":"api.example.com" ,  "ANOTHER_API_URL" : "anotherapi.example.com" }'
                   KEY: VALUE 
                 EOF
            outputs:
              - name: cf_command
        - put: run-container-image
          inputs:
            - cf_command
            - app-repo
          resource: cf-sandbox
          params:
            command: push
            command_file: cf_command/params.yml

```

logs from concourse 

```
Using manifest file /tmp/build/put/manifest-for-environment-variables.yml


Deprecation warning: Specifying app manifest attributes at the top level is deprecated. Found: env.
Please see https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#deprecated for alternatives and other app manifest deprecations. This feature will be removed in the future.


Using manifest file manifest-for-environment-variables.yml
```

_Originally posted by @destasys in https://github.com/nulldriver/cf-cli-resource/issues/74#issuecomment-604009766_

**Comment by patrickcrocker** [comment]
Sorry, but I'm unable to reproduce your issue.  I used a modified version of your pipeline and it seems that the environment variables are properly set:

pipeline.yml
```
---
jobs:
- name: deploy-to-sandbox
  plan:
  - task: create-deploy-params
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      run:
        path: sh
        args: 
          - -exc
          - |- 
            cat > cf_command/params.yml <<EOF
            docker_image: nulldriver/test-app
            command: push
            app_name: test-app
            instances: 2
            memory: 512M
            environment_variables:
              SITE_SETTINGS: '{"API_URL":"api.example.com" ,  "ANOTHER_API_URL" : "anotherapi.example.com" }'
              KEY: VALUE 
            EOF
      outputs:
        - name: cf_command
  - put: run-container-image
    inputs:
      - cf_command
    resource: cf-sandbox
    params:
      command: push
      command_file: cf_command/params.yml

resources:
- name: cf-sandbox
  type: cf-cli-resource
  source:
    api: ((cf-api))
    username: ((cf.username))
    password: ((cf.password))
    org: test
    space: test

resource_types:
- name: cf-cli-resource
  type: docker-image
  source: 
    repository: nulldriver/cf-cli-resource
    tag: 2.18.0
```

And here we can see the variables set:
```bash
$ cf env test-app
Getting env variables for app test-app in org test / space test as admin...
OK

System-Provided:


{
 "VCAP_APPLICATION": {
(redacted)
}

User-Provided:
KEY: VALUE
SITE_SETTINGS: {"API_URL":"api.example.com" ,  "ANOTHER_API_URL" : "anotherapi.example.com" }

No running env variables have been set

No staging env variables have been set
```
