### ISSUE TITLE
`wait_for_service` doesn't seem to wait for the service.

### ISSUE THREAD

**Issue by tammersaleh** [nulldriver/cf-cli-resource#77]
`wait_for_service` doesn't seem to actually wait for the service.  

The concourse snippet is:

``` yaml
- put: create-db                                      
  resource: cf-cli-dev                                
  params:                                 
    command: create-service                           
    update_service: true                              
    wait_for_service: true                            
    timeout: 1200    # RDS take a long time to provision
    service_instance: stratos-db                      
    service: aws-rds                                  
    plan: medium-psql                                 
```

This is using the https://github.com/18F/aws-broker, which provisions AWS RDS instances, which take a looong time.

In the concourse logs, I see:

```
15:17:58  [INFO] Waiting for service: stratos-db
15:17:59  [INFO] Service is ready: stratos-db
```

Only waited one second.  The subsequent deployment then fails saying the service instance isn't ready.  I'll then go to the AWS console and see that the instance is still being created.  Later, re-running the build, the deployment will pass.  It's just as likely that this is a bug in the  https://github.com/18F/aws-broker, but wanted to record it here just in case it's a known issue.

**Comment by patrickcrocker** [comment]
Thanks for reporting.  I'll try to reproduce in a test case, stay tuned.

**Comment by patrickcrocker** [comment]
I'm unable to reproduce this in my environment:
- [PCF v2.8.5](https://network.pivotal.io/products/elastic-runtime#/releases/596319) (cloud controller: v2.142 / v3.77.0)
- [Pivotal Mysql v2.7.6](https://network.pivotal.io/products/pivotal-mysql#/releases/584606)

At the heart of the `wait_for_service` functionality is polling the cloud controller for the [last operation state](https://github.com/nulldriver/cf-cli-resource/blob/v2.18.1/resource/lib/cf-functions.sh#L509) of the service.  If the `succeeded` state is returned then the service is up.

Can you run a simple test from the command line and post the sanitized output?

1. cf target
2. cf create-service aws-rds medium-psql stratos-db
3. cf cf curl "/v2/service_instances/$(cf service stratos-db --guid)"

**Comment by patrickcrocker** [comment]
Oh, and here is my Concourse output and pipeline for my test:

https://ci.nulldriver.com/teams/resources/pipelines/create-and-wait-for-service/jobs/create-and-wait-for-service/builds/1

```
---
jobs:
- name: create-and-wait-for-service
  public: true
  plan:
  - put: cloud-foundry
    params:
      commands:
      - command: create-org
      - command: create-space
      - command: create-service
        service: p.mysql
        plan: db-small
        service_instance: my-db
        wait_for_service: true

resources:
- name: cloud-foundry
  type: cf-cli-resource
  source:
    api: https://api.run.nulldriver.com
    username: ((cf.username))
    password: ((cf.password))
    org: examples
    space: create-and-wait-for-service

resource_types:
- name: cf-cli-resource
  type: registry-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest
```
