### ISSUE TITLE
Add support for `cf curl`

### ISSUE THREAD

**Issue by BartoszKaszewczuk** [nulldriver/cf-cli-resource#79]
Some of the CF functionalities are exposed only via CF REST endpoints.
To configure them one can use CF CLI's `cf curl ...` eg: 
```
cf curl /v2/route_mappings -X POST -d '{"app_guid": "someUUID", "route_guid": "someOtherUUID", "app_port": 9000}'
```
This is to add support for `cf curl` to `cf-cli-resource`.

**Comment by patrickcrocker** [comment]
I'm curious as to how you would use this in a pipeline.  Do you have an example pipeline.yml that might show how you would use `cf curl`?  (the example you gave would certainly list out the route mappings, but I'm not seeing how that would be useful in a CI/CD pipeline.  Thanks!

**Comment by BartoszKaszewczuk** [comment]
Sure @patrickcrocker 

### Use case:
Using `cf-cli-resource` to configure cloud environments/deployments.
CF by default binds to container port `8080`. If container doesnt expose 8080 or exposes more ports then CF will bind to a port of choice which may not be a desired one. This can be overridden via CF REST API accessible via `cf curl`. 

I came up with 4 possible options ordered by ~complexity (minus most basic usage) and personally actually made me think that `option 4.` would open flexibility to additionally cover many more exotic cluster/deployment manipulation needs.

### Sample usage:
```yaml
pipeline:
  - put: apply-config-file
    resource: cf-env
    params:
      cf_home: cf-deployer-development
      space: ((cf-space-development))
      commands:
        - command: curl
          requests: >
            # Options:
            # 1. One request per line
            /v2/route_mappings -X POST -d '{"app_guid": "someUUID", "route_guid": "someOtherUUID", "app_port": 9000}'
            /v2/route_mappings -X POST -d '{"app_guid": "someUUID", "route_guid": "someOtherUUID", "app_port": 9000}'

            # 2. Using pipe operator to allow command chaining
            /v2/route_mappings -X POST -d '{"app_guid": "someUUID", "route_guid": "someOtherUUID", "app_port": 9000}' &&
            /v2/route_mappings -X POST -d '{"app_guid": "someUUID", "route_guid": "someOtherUUID", "app_port": 9000}'

            # 3. Allow for shell execution with cf-cli in path to able to execute more complex commands
            #     Note: since this pattern allows for even more flexibility, the command name should be different eg shell
            cf curl /v2/route_mappings -X POST -d '{"app_guid": "$(cf app service-discovery-dev --guid)", "route_guid": "someOtherUUID", "app_port": 9000}' |
            cf curl /v2/route_mappings -X POST -d '{"app_guid": "someUUID", "route_guid": "someOtherUUID", "app_port": 9000}'

            # 4. Allow for raw shell script execution with cf-cli in path to able to execute even more complex manipulations against CF
          script_file: ((program-source-master))/ci/post-configure-deployment.sh
```
