### ISSUE TITLE
cf-cli-resource has no version

### ISSUE THREAD

**Issue by giva01121** [nulldriver/cf-cli-resource#92]
Hello, I'm getting an error `cf-cli-resource has no version`, so later I've put `cf_cli_version: 7` but again I'm getting the same error

```
resource_types:
- name: cf-cli-resource
  type: registry-image
  source:
    cf_cli_version: 7
    repository: nulldriver/cf-cli-resource
    tag: latest
```
